# Generated by Django 3.2 on 2021-04-19 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('api_key', models.CharField(db_index=True, max_length=255, verbose_name='API_KEY')),
                ('api_secret', models.CharField(db_index=True, max_length=255, verbose_name='API_SECRET')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, verbose_name='Order id')),
                ('symbol', models.CharField(db_index=True, max_length=255, verbose_name='Symbol')),
                ('ord_type', models.PositiveSmallIntegerField(choices=[(1, 'Market'), (3, 'Stop'), (5, 'MarketIfTouched'), (7, 'Pegged')], verbose_name='Order type')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')], verbose_name='Side')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Volume')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.account')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
